#!/bin/sh

state=/sys/devices/platform/imx8m-cm4/remoteproc/remoteproc0/state
if [ ! -f "$state" ]; then
  state=/sys/kernel/debug/remoteproc/remoteproc0/state
fi


if [ "$1" = "start" ]; then
  if [ -n "$2" ]; then
    echo stop > "$state"
    if ! cp "$2" /lib/firmware/rproc-imx-rproc-fw; then
      echo "Failed to copy firmware" 1>&2
      exit 1
    fi
  fi
  echo start > "$state"
elif [ "$1" = "stop" ]; then
  echo stop > "$state"
else
  (
  echo "usage: $(basename $0) start [path/firmware.elf]"
  echo "       $(basename $0) stop"
  ) 1>&2
  exit 1
fi
