#!/bin/bash
set -e

m4build 
cd build

bin=$1

binaries="$(ls debug/*.bin | wc -l)"
if [[ -z "$bin" ]]; then
  if [[ "$binaries" -eq 1 ]]; then
    bin="$(basename debug/*.bin)"
  else
    echo Which m4 application to run?:
    (cd debug && find . -name '*.bin' | xargs -I{} basename {} .bin | sed "s/^/  $ m4run /")
    exit 1
  fi
fi

echo stop > /sys/kernel/debug/remoteproc/remoteproc0/state
cp "debug/$bin" /lib/firmware/rproc-imx-rproc-fw
echo start > /sys/kernel/debug/remoteproc/remoteproc0/state

#m4ctl load "debug/$bin" "$@"
